# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a restaurant category (e.g. Tex-Mex, Chinese)', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.IntegerField()),
                ('monday_end', models.IntegerField()),
                ('tuesday_start', models.IntegerField()),
                ('tuesday_end', models.IntegerField()),
                ('wednesday_start', models.IntegerField()),
                ('wednesday_end', models.IntegerField()),
                ('thursday_start', models.IntegerField()),
                ('thursday_end', models.IntegerField()),
                ('friday_start', models.IntegerField()),
                ('friday_end', models.IntegerField()),
                ('saturday_start', models.IntegerField()),
                ('saturday_end', models.IntegerField()),
                ('sunday_start', models.IntegerField()),
                ('sunday_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('res_id', models.TextField(default='NULL', help_text='Unique ID for the restaurant', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=50)),
                ('longtitude', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('image_url', models.CharField(default='None', max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=5)),
                ('zipcode', models.CharField(max_length=10)),
                ('price', models.CharField(default='None', max_length=5)),
                ('yelp_url', models.CharField(default='None', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='YelpReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(help_text='Reviewed by the Yelp User', max_length=200)),
                ('review_user', models.CharField(max_length=50)),
                ('ri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='hour',
            name='res',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant'),
        ),
        migrations.AddField(
            model_name='category',
            name='res_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Restaurant'),
        ),
    ]
