# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_yelpreview_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='friday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='friday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='monday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='monday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='saturday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='saturday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='sunday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='sunday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='thursday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='thursday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='tuesday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='tuesday_start',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='wednesday_end',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='hour',
            name='wednesday_start',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
