# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0006_auto_20170918_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='favby',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='favby',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
