# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_restaurant_favby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': (('can_mark_fav', 'Set restaurant as favorited'), ('can_mark_unfav', 'Remove restaurant from favorite list'), ('can_add_note', 'Add a note to a restaurant'), ('can_delete_note', 'Remove a note to a restaurant'))},
        ),
    ]
