# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170919_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkrestaurant',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='bookmarkrestaurant',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookmarkRestaurant',
        ),
    ]
