# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170914_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpreview',
            name='review_url',
            field=models.CharField(default='None', max_length=350),
        ),
    ]
