# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20170918_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'bookmark_restaurant',
            },
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='favby',
        ),
        migrations.AddField(
            model_name='bookmarkrestaurant',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant', verbose_name='Restaurant'),
        ),
        migrations.AddField(
            model_name='bookmarkrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
